#!/bin/sh
#
# Starts wlan notify service
#

start() {

	# Update network status
	echo X > /etc/network/status
	chmod 644 /etc/network/status

	printf "Starting wlan notify: "
	start-stop-daemon -S -q -p /var/run/wlan-notify.pid \
		--exec /usr/sbin/wlan-notify.sh
		[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping wlan notify: "
	echo X > /etc/network/status
	start-stop-daemon -K -q -p /var/run/wlan-notify.pid
		[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
;;
  stop)
	stop
;;
  restart|reload)
	restart
;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

