#!/bin/sh
#
# brcmfmac        Background loading of wireless driver
#

umask 077

start() {
	/sbin/modprobe brcmfmac &
	echo "brcmfmac loading in background" > /dev/kmsg
	echo "OK"
}
stop() {
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
